# Generated by Django 4.2 on 2023-05-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutenticacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
