# Generated by Django 4.2 on 2023-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPedidos', '0002_alter_detallepedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_al_momento',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.FloatField(editable=False),
        ),
    ]
